//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class AlbumHasTrack
    {
        public int Id { get; set; }
        public string AlbumId { get; set; }
        public string TrackId { get; set; }
    
        public virtual AlbumTable AlbumTable { get; set; }
        public virtual TrackTable TrackTable { get; set; }
    }
}
